name: todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  date_picker_plus: ^2.1.0
  day_night_time_picker: ^1.3.0+1
  emoji_picker_flutter: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_datetime_picker: ^1.5.1
  flutter_iconpicker: ^3.4.4
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: ^3.0.4
  flutter_time_picker_spinner: ^2.0.0
  icon_checkbox: ^1.0.1
 
  
  intl: ^0.18.1
  isar: ^3.1.0+1
  page_transition: ^2.1.0
  provider: ^6.1.1
  rive: ^0.13.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - RiveAssets\background.riv
